### PR TITLE
Drt Fares

### PR DESCRIPTION
**Pull request by tschlenther**
Adopt to [recent changes in DRT](https://github.com/matsim-org/matsim-libs/pull/1192#issuecomment-704732394) (DrtFares are now a parameter set inside `DrtConfigGroup`)
@vsp-gleich please check whether your intermodal stuff is adopted correctly..

### CODE REVIEW

**Review by vsp-gleich — APPROVED** [review]
I rewrote a part to remove preconditions which are not necessary and caused test failures. It should be ok now.

**Comment by vsp-gleich** [comment]
Ah, drt fares have not been replaced in the drtSpeedUp repository. For that reason RunDrtOpenBerlinScenarioWithDrtSpeedUpTest fails. Since drtSpeedUp is to be replaced soon I'm not sure whether it is planned to adapt that repository or to directly replace drtSpeedUp repository with the new version in the drt contrib. So maybe we have to wait for the new version to come and insert it here. If a new version of matsim-berlin is needed urgently please adapt the existing drtSpeedUp repository.

**Comment by vsp-gleich** [comment]
All other tests now run through

**Comment by tschlenther** [comment]
@michalmac would it be possible for you to update the corresponding run scripts in matsim-berlin as soon as you have finished your work on the teleportation enginge?
That would be very nice :)

**Comment by michalmac** [comment]
Sorry. Forgot to mention that I have updated all input configs in quite a few projects I have checked out in my IntelliJ.

So I have changes to configs committed locally. I have not pushed them because I noticed that many projects use some snapshot versions (and therefore I could not adapt code). These projects are:
- avoev
- drt-speed-up
- matsim-analysis
- matsim-berlin
- opt-drt
- pave
Please let me know which of them I should update (the snapshot version, code and configs).

**Comment by michalmac** [comment]
> Sorry. Forgot to mention that I have updated all input configs in quite a few projects I have checked out in my IntelliJ.
I meant changes to the taxi/drt fares configs.

**Comment by tschlenther** [comment]
> So I have changes to configs committed locally. I have not pushed them because I noticed that many projects use some snapshot versions (and therefore I could not adapt code). 

WIth snapshots you mean older versions than [#1191](https://github.com/matsim-org/matsim-libs/pull/1192#issuecomment-704732394) ?

> 
>     * avoev
> 
>     * drt-speed-up
> 
>     * matsim-analysis
> 
>     * matsim-berlin
> 
>     * opt-drt
> 
>     * pave
>       Please let me know which of them I should update (the snapshot version, code and configs).

I suppose, if you already have the adopted configs, it would be nice to have them in all of the projects..
I can speak for pave and matsim-berlin at least.
drt-speed-up might become obsolete after though as @vsp-gleich mentioned..

**Comment by vsp-gleich** [comment]
> > Sorry. Forgot to mention that I have updated all input configs in quite a few projects I have checked out in my IntelliJ.
> 
> I meant changes to the taxi/drt fares configs.

If you have already refactored the old drt-speed-up repository maybe just push it and we point to the updated drt-speed-up version here to make the failing test run. Otherwise we might just wait for the new drt speed up to be ready.

**Comment by michalmac** [comment]
I only refactored configs. I could not refactor code as some older matsim snapshots are used there (so I would get compile errors).

For example, for avoev we have : `<matsim.version>12.0-2020w04-SNAPSHOT</matsim.version>`. I guess updating to the latest may cause lots of problems related to lots of changes to matsim done in the meantime.

So my question is: Which of the listed projects (besides pave and matsim-berlin that @tschlenther named) I can safely update to the most recent matsim snapshot? Maybe there are also some projects I am not aware of?

I will probably do it in 2 steps (1. fares, 2. speedup).

**Comment by vsp-gleich** [comment]
> For example, for avoev we have : `<matsim.version>12.0-2020w04-SNAPSHOT</matsim.version>`. I guess updating to the latest version may cause lots of problems as lots of changes have been done in matsim in the meantime.
Yes indeed, avoev is stuck on that old matsim version for various reasons. Just ignore avoev. This project will be finished soon anyway. 

> So my question is: Which of the listed projects (besides pave and matsim-berlin that @tschlenther named) can I safely update to the most recent matsim snapshot? Maybe there are also some projects I am not aware of?
You can update to the newest matsim snapshot in all other projects:
* drt-speed-up (if not replaced immediatley by the version in the drt contrib)
* matsim-analysis
* matsim-berlin
* opt-drt
* pave
Maybe someone is using the vsp-playgrounds.

> I will probably do it in 2 steps (1. fares, 2. speedup).
I think that approach would mean that you have to replace the old drt fares in the old drt-speed-up repository in order to get all projects using fares and speed up running to accomplish 1). And then later replace anyway while doing 2)

**Comment by michalmac** [comment]
Thanks for the list.

> Maybe someone is using the vsp-playgrounds.

That I have already pushed (was easy - as the latest matsim snapshot is used there).

>> I will probably do it in 2 steps (1. fares, 2. speedup).

> I think that approach would mean that you have to replace the old drt fares in the old drt-speed-up repository in order to get all projects using fares and speed up running to accomplish 1). And then later replace anyway while doing 2)

Yeah. I prefer moving in smaller steps with propagating (disjoint) change sets through many repos.

**Comment by michalmac** [comment]
I have propagated the changes in drt/taxi fares to all projects (except for avoev). In some cases, I had to adapt a bit more, as the weekly snapshots weren't super recent.

I had to depend on the current snapshot and not the weekly, as the latter has not been deployed yet after the changes in fares. I guess we can live with that for a few days...

**Pull request closed without merging**
