### PR TITLE
Add github actions testing

### PR DESCRIPTION
**Pull request by vsp-gleich**
Our old travis service has shut down. Apply Github Actions instead.

### CODE REVIEW

**Comment by vsp-gleich** [comment]
There is RunOfflineAirPollutionAnalysisTest failing because it needs a password set as an environment variable. I have no idea how this could work with Github Actions (and then likely with the password still being secret). I set the test to ignore to have any ci working for the other tests at least. Whoever feels responsible for that test can attempt to include it in Github actions @ikaddoura @kt86.

**Comment by tschlenther** [comment]
normally would say that this PR is pretty important and we should merge it soon. Not sure about the test, though...

**Comment by vsp-gleich** [comment]
The current situation is that the aforementioned test exists but is never run like all other tests are not run any longer since travis has shut down. Merging the pull request means we reactivate all tests except that one (and we update some dependencies which might cause some hopefully small random changes). I already merged github actions ci to the 5.6 / master branch, so this is not essential for future development.

**Review by tschlenther — APPROVED** [review]

**Comment by kt86** [comment]
Thanks for reactivating all the other tests and moving to github actions! 
I created an Issue for the RunOfflineAirPollutionAnalysisTest. Hopefully @rakow has a good idea :)
If not, we have to think about how to deal with it.

**Pull request merged**
